# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.7'
services:
  password_generator:
      container_name: password_generator
      image: wisrovi/password_generator:V1.0
      ports:
         - 5050:80
      deploy:
         resources:
           limits:
             cpus: "0.50"
             memory: 512M
           reservations:
             cpus: "0.25"
             memory: 128M
      restart: always
      privileged: true

  
  mongo:
    image: mongo:5.0.6
    container_name: mongo
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
          limits:
            cpus: "0.50"
            memory: 512M
          reservations:
            cpus: "0.25"
            memory: 128M
    command: --wiredTigerCacheSizeGB 1.5
    #ports:
    #  - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8079:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    deploy:
      resources:
          limits:
            cpus: "0.50"
            memory: 512M
          reservations:
            cpus: "0.15"
            memory: 64M
  
volumes:
  config:
  database:
